### ISSUE TITLE
Use Option key instead of Control key for hiding

### ISSUE THREAD

**Issue by uliwitness** [retrospectmike/MacDock#18]
MacOS 9 already supports holding down the Option Key while switching applications to hide the one you're leaving. So I'd recommend using that key for the similar functionality in MacDock.

Also, Ctrl-Click in later MacOS versions (I think starting with 8?) is used for context menus (basically, "right click" just that Mac mice had no right mouse button), so I'd save that for a popup menu with options or so.

**Comment by retrospectmike** [comment]
This is a good point -- fortunately the readme's "control + click" is a typo and it should read option + click!  So it already has been working as your issue recommends.  
In fact, there is no custom code for this within MacDock.  Instead, the OS already notices that option is being held down when the app-change is happening so it natively handles hiding the app you're leaving!

Thx. for the issue raising!!!
