### ISSUE TITLE
There is no “macOS System 7”

### ISSUE THREAD

**Issue by mattl** [retrospectmike/MacDock#2]
It’s just System 7 or later Mac OS.

**Comment by retrospectmike** [comment]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/69996986/235825823-3a26ebf0-82f7-480a-891a-a5cf4d25055d.png">

Current operating system (with the modern Dock) is macOS (see above link).
For a while it was Mac OS X before that (introduced the Dock)
Before that was Mac OS (eg Mac OS 9)
Before that was System (as in System 7)

When I say macOS I mean [macOS](https://www.apple.com/macos/ventura/)

Edit - that being said, I agree that there is no 'macOS System 7' -- if I used that phrase somewhere let me know where!

**Comment by mattl** [comment]
“ Like the macOS Dock... but for MacOS System 7” makes no sense then

**Comment by retrospectmike** [comment]
Could you point to where in the repo's documents I say that?  
Here's a pic of the current ReadMe.md below.  It doesn't say `MacOS System 7`.. is there somewhere else where the phrasing is used?
Thanks for keeping me on my toes!

<img width="669" alt="image" src="https://user-images.githubusercontent.com/69996986/235826487-fa851979-fc8a-4897-9df3-bb5b70808fc9.png">

**Comment by mattl** [comment]
![IMG_7939](https://user-images.githubusercontent.com/33296/235826710-fd1d0af1-7d55-46b9-afad-c5fd9291c712.png)

**Comment by retrospectmike** [comment]
Ah I see it now!  I was scouring the documents but the git repo's Description had it.  You the man!  
Ok fixed it - thanks!!!!

**Comment by mattl** [comment]
Thank you. I’ll dig a classic Mac out this week and try it out too ❤️
